[versions]
agp = "8.5.0"                  # Android Gradle Plugin
kotlin = "2.0.0"               # Kotlin
coreKtx = "1.13.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.2"
constraintlayout = "2.1.4"
junit = "4.13.2"
extJunit = "1.2.1"
espressoCore = "3.6.1"
mpandroidchart = "3.1.0"
jtds = "1.3.1"
javamail = "1.6.7"
javamailActivation = "1.6.7"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
activity = { module = "androidx.activity:activity", version.ref = "activity" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
junit = { module = "junit:junit", version.ref = "junit" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "extJunit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
jtds = { module = "net.sourceforge.jtds:jtds", version.ref = "jtds" }
android-mail = { module = "com.sun.mail:android-mail", version.ref = "javamail" }
android-activation = { module = "com.sun.mail:android-activation", version.ref = "javamailActivation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }